# Generated by Django 5.2.17 on 2026-08-18 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заказа')),
                ('months', models.PositiveSmallIntegerField(default=3, verbose_name='Срок, мес.')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Наценка за весь срок, %')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'Рассрочка активна'), ('closed', 'Погашен'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client.client', verbose_name='Клиент')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchant.merchant', verbose_name='Мерчант')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер платежа')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'График платежей',
                'ordering': ['order', 'number'],
                'constraints': [models.UniqueConstraint(fields=('order', 'number'), name='uniq_payment_number_per_order')],
            },
        ),
    ]
