# Generated by Django 5.2 on 2026-07-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('installment', '0002_initial'),
        ('merchandise', '0002_initial'),
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_orders', to='user.client', verbose_name='Mijoz'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders', to='company.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders', to='merchandise.duration', verbose_name='Muddati'),
        ),
        migrations.AddField(
            model_name='draftorderproduct',
            name='draft_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.draftorder', verbose_name='Qoralama buyurtma'),
        ),
        migrations.AddField(
            model_name='draftorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_order_items', to='merchandise.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='merchantpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payments', to='company.company', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='merchantpaymentexport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payment_exports', to='company.company', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='merchantpaymentexport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_payment_exports', to='user.role', verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='company.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.client', verbose_name='Mijoz'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='company.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='user.role', verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchandise.duration', verbose_name='Muddati'),
        ),
        migrations.AddField(
            model_name='merchantpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payments', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderadditionalservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderadditionalservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.additionalserviceprice', verbose_name='Xizmat turi'),
        ),
        migrations.AddField(
            model_name='orderotp',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_otps', to='user.client', verbose_name='Mijoz'),
        ),
        migrations.AddField(
            model_name='orderotp',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='merchandise.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='merchantpayment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payments', to='order.orderproduct', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='orderreceiptimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_images', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa Client tomonidan o'zgartirilgan", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_logs', to='user.role', verbose_name='Kim tomonidan'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='order.orderstatuslog', verbose_name='Oldingi status log'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='order.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='radiusorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.radiusorder', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='temporaryorderdata',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_order_data', to='installment.application', verbose_name='Vaqtinchalik zakaz'),
        ),
        migrations.AddField(
            model_name='temporaryorderdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_order_data', to='user.client', verbose_name='Mijoz'),
        ),
        migrations.AddIndex(
            model_name='orderotp',
            index=models.Index(fields=['client', 'order', 'is_verified'], name='order_order_client__cb4b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('imei',), name='unique_active_product_imei'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['order', '-created_at'], name='order_order_order_i_c56095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('order', 'period_number')},
        ),
    ]
