# Generated by Django 5.2 on 2026-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorderproduct',
            name='ikpu',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='IKPU'),
        ),
        migrations.AddField(
            model_name='draftorderproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_type',
            field=models.CharField(choices=[('manually', "Qo'lda (merchant)"), ('mobile', 'Mobil ilova')], db_index=True, default='manually', help_text="Buyurtmani merchant qo'lda kiritdimi yoki mijoz ilova orqali yaratdimi", max_length=20, verbose_name='Yaratilish usuli'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='ikpu',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='IKPU'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('marketplace', 'Marketplace')], default='offline', max_length=20, verbose_name='Buyurtma manbasi'),
        ),
    ]
